menu:
  about: /about
  archives: /archives

excerpt: true
feed: /atom.xml
repo: https://icylogic.net

duoshuo:

cdn:
  normalize: 'https://cdnjs.cloudflare.com/ajax/libs'
  carbon: ''
  duoshuo: '//static.duoshuo.com'
  jQuery: 'https://cdnjs.cloudflare.com/ajax/libs'
  pjax: 'https://cdnjs.cloudflare.com/ajax/libs'
